

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quizzy
      - SPRING_DATASOURCE_USERNAME=quizzy
      - SPRING_DATASOURCE_PASSWORD=quizzy123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - db

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: quizzy
      POSTGRES_USER: quizzy
      POSTGRES_PASSWORD: quizzy123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/static/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./backend/src/main/resources/static/seeddata.sql:/docker-entrypoint-initdb.d/02_seeddata.sql:ro

volumes:
  db_data:
